### PR TITLE
Libcurl 7 50 1

### PR DESCRIPTION
**Pull request by chcg**
- updated with unchanged complete data from https://curl.haxx.se/download/curl-7.50.1.zip, see https://curl.haxx.se/changes.html for the various security related bugfixes (in the meantime 7.54.0 is the current version, but that one is much easier to integrated after this PR, as the new curl version could be used without project specific modifications)
- modified VS project nmake call to remove the dependency to msvcr dll without modifying curl itself, corresponding to modified curl/winbuild/MakefileBuild.vc in checkin c5e23fc
- this would also enable the option to add libcurl as git submodule from https://github.com/curl/curl instead of coping the code, but probably that is no option as the RN says:

REMEMBER: these "releases" on github are only the entire source code repo at the time of the tag put into a compressed file, they are not identical to the officially blessed release tarballs found on the web site. The release tarballs get a bunch of files included that are generated in the release process, and these github "releases" do not.

### CODE REVIEW

**Comment by GitMensch** [comment]
@donho: Any chance for including this merge request? Despite the possibility to finally fix https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1237 curl has many CVEs listed and getting these fixes in help a lot...

@chcg: Will you provide another merge request for updating to curl 7.54.1, afterwards?

**Comment by chcg** [comment]
@GitMensch After the merge of this PR the update to curl 7.54.1 could be added directly from https://curl.haxx.se/download.html archive. I could also extend this PR or create a new one if requested by donho.

**Comment by donho** [comment]
@chcg Thank you for the PR
However, I have updated to the latest version of cURL: 0ba3c3077976cf6618fe6b5a0d469519eabc5abf

**Comment by donho** [comment]
@GitMensch  By following the hint of #1237, this issue should be fixed.
Could you try and validate the fix?

**Pull request closed without merging**
